language: python
python: 3.7.9
dist: xenial
install:
  - sudo apt-get update || true
  - sleep 10
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda || true
  # Useful for debugging any issues with conda
  - conda info -a

  #- conda config --set channel_priority strict
  - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f nrCascadeSim_env.yml 
  - source activate test-environment

  # Snap installation of root
  #- sudo apt-get install snap
  #- sudo snap install root-framework
  #- sudo run root-framework

  # Useful for debugging version of emcee 
  #- echo 'Conda searching emcee:'
    #- conda search emcee
  #- echo 'Python Version:'
  #- echo $TRAVIS_PYTHON_VERSION
  #- conda list |grep emcee 

#  - conda install root

  # Get ROOT via binary
  - wget https://root.cern/download/root_v6.22.00.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
  - tar -xzvf root_v6.22.00.Linux-ubuntu16-x86_64-gcc5.4.tar.gz
  - sudo apt-get install make cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev openssl libssl-dev
  - source root/bin/thisroot.sh

  - make

before_script: cd example-usecase 

script:
- travis_wait 50 py.test
- cd ../
- bin/realizeCascades -n 100000 -o "output.root?reproducible=fixedname" -d 1 levelfiles/Si28_ngam_all_cascades_rfmt_sorted.txt
- md5sum output.root
- md5sum output.root | awk '{if ($1=="2029e8b402b89d3a05d745e48f546370"){print"Checksum passed!"} else {exit 1}}'
# NOTE that the checksum seems for some reason to be dependent on the relative path given
